/*
 * SPDX-FileCopyrightText: 2026 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";

const rootDir = join(import.meta.dirname, "..", "..");
const schemaPath = join(rootDir, "src", "data", "daily-seed", "schema.json");
const outputPath = join(rootDir, "src", "data", "daily-seed", "schema-validator.generated.ts");
const schemaId = "custom-daily-run";

const generatedFileHeader = `/*
 * SPDX-FileCopyrightText: 2026 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file is generated by scripts/daily-seed/generate-schema-validator.ts.
// Run \`pnpm generate:daily-seed-validator\` after changing schema.json.
// @ts-nocheck -- Ajv emits JavaScript without TypeScript annotations.
// biome-ignore-all lint: This file contains generated Ajv validation code.
// biome-ignore-all format: Preserve deterministic Ajv generator output.

import type { CustomDailyRunConfig } from "#types/daily-run";

export interface DailySeedSchemaValidationError {
  readonly instancePath: string;
  readonly schemaPath: string;
  readonly keyword: string;
  readonly params: Readonly<Record<string, unknown>>;
  readonly message?: string;
}

export interface DailySeedSchemaValidator {
  (data: unknown): data is CustomDailyRunConfig;
  errors: readonly DailySeedSchemaValidationError[] | null;
}

`;

function generateValidatorModule(inputSchema: object): string {
  const ajv = new Ajv({
    allErrors: true,
    code: {
      esm: true,
      lines: true,
      optimize: true,
      source: true,
    },
  });
  ajv.addSchema(inputSchema, schemaId);

  const moduleCode = standaloneCode(ajv, { validateDailySeedSchema: schemaId })
    .replace('"use strict";\n', "")
    .replace(
      /export const validateDailySeedSchema = ([A-Za-z_$][\w$]*);/,
      "export const validateDailySeedSchema = $1 as DailySeedSchemaValidator;",
    );

  if (!moduleCode.includes("export const validateDailySeedSchema =")) {
    throw new Error("Ajv standalone output did not contain the expected validator export");
  }

  return `${generatedFileHeader}${moduleCode.trimEnd()}\n`;
}

async function readCurrentOutput(): Promise<string | undefined> {
  try {
    return await readFile(outputPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }
    throw error;
  }
}

const dailySeedSchema = JSON.parse(await readFile(schemaPath, "utf8")) as object;
const generatedOutput = generateValidatorModule(dailySeedSchema);
const currentOutput = await readCurrentOutput();

if (process.argv.includes("--check")) {
  if (currentOutput === generatedOutput) {
    console.log("The generated daily-seed validator is up to date.");
  } else {
    console.error(
      "The generated daily-seed validator is stale. Run `pnpm generate:daily-seed-validator` and commit the result.",
    );
    process.exitCode = 1;
  }
} else if (currentOutput === generatedOutput) {
  console.log("The generated daily-seed validator is already up to date.");
} else {
  await writeFile(outputPath, generatedOutput, "utf8");
  console.log(`Generated ${outputPath}`);
}
